darts/darts/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('', include('search.urls')),
    path("admin/", admin.site.urls),
    # path("", TemplateView.as_view(template_name="sample_index.html"), name="home"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

darts/search/urls.py
from django.urls import path
from . import views
from search.views import CaseView, Search, Upload

urlpatterns = [
    path('', Search.as_view(), name='search'),
    path('search/', Search.as_view(), name='search'),
    path('upload/', Upload.as_view(), name='upload'),
    path('list/', views.list, name='list'),
    path('cases/<int:id>/', CaseView.as_view(), name='case'),
    path('documents/<int:id>/', views.view_doc, name='document'),
    path('documents/<int:id>/<slug:slug>/', views.view_doc, name='document'),
    path('current_user/set/<int:id>/', views.set_user, name='set_user'),
]

darts/search/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.postgres.search import SearchVectorField
from django.template.defaultfilters import slugify

class Region(models.Model):
    name = models.CharField(max_length=255)
    number = models.IntegerField()
    # has_many :cases

    def __str__(self):
        return f"Region {self.number}: {self.name}"


class Case(models.Model):
    name = models.CharField(max_length=255)
    public = models.BooleanField(default=False)
    # has_many :documents
    # belongs_to :region
    region = models.ForeignKey(Region, on_delete=models.CASCADE, null=True)

    alias = models.CharField(max_length=255, null=True)
    state = models.CharField(max_length=255, null=True)
    location = models.CharField(max_length=255, null=True)
    contaminants_of_concern = models.CharField(max_length=255, null=True)
    affected_doi_resources = models.TextField(null=True)
    incident_type = models.CharField(max_length=255, null=True)
    status = models.CharField(max_length=255, null=True)
    authority = models.CharField(max_length=255, null=True)
    description = models.TextField(null=True)
    contact = models.CharField(max_length=255, null=True)
    trustees = models.TextField(null=True)

    def photos(self):
        return [
            {
                'src': "https://www.cerc.usgs.gov/orda_docs/PhotoHandler.ashx?ID=149&task=displayAll",
                'caption': "Credit: Exxon Valdez Trustee Council"
            },
            {
                'src': "https://www.cerc.usgs.gov/orda_docs/PhotoHandler.ashx?ID=152&task=displayAll",
                'caption': "Barge water tanks, workers hosing beach, Credit: Exxon Valdez Trustee Council"
            }
        ]


    def lonlat(self):
        return [60.614279,-147.0847959]

    def zoom(self):
        return 8

    def contaminants_list(self):
        return self.contaminants_of_concern.split(", ")


    def contact_object(self):
        name, address, phone, website, *rest = self.contact.split(" | ")
        return {
            'name': name,
            'address': address,
            'phone': phone,
            'website': website,
            'rest': rest
        }


    def resource_list(self):
        return self.affected_doi_resources.split(", ")


    def trustees_list(self):
        return self.trustees.split(", ")


    def __str__(self):
        return self.name


class Document(models.Model):
    body = models.TextField()
    file = models.BinaryField()
    filename = models.CharField(max_length=255)
    filename_normal = models.CharField(max_length=255)
    search_text = SearchVectorField()
    title = models.CharField(max_length=255)
    # slug should be null=False, unique=True, default=slugify(self.title) but can't figure out how to do that.
    slug = models.SlugField(max_length=255, null=True)
    public = models.BooleanField(default=False)

    # belongs_to :case
    case = models.ForeignKey(Case, on_delete=models.CASCADE, null=True)

    # belongs_to :region, through: :case
    def region(self):
        if self.case:
            return self.case.region

    def save(self, *args, **kwargs):  # new
        if self.title:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    # Override insert and update methods to prevent inserting/updating search_text directly
    def _do_insert(self, manager, using, fields, update_pk, raw):
        return super(Document, self)._do_insert(
            manager, using,
            [f for f in fields if f.attname not in ['search_text']],
            update_pk, raw)

    def _do_update(self, base_qs, using, pk_val, values, update_fields, forced_update):
        return super(Document, self)._do_update(
            base_qs, using, pk_val,
            [f for f in values if f[0].attname not in ['search_text']],
            update_fields, forced_update)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("document", kwargs={ "id": str(self.id), "slug": str(self.slug) })


class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    first_name = models.CharField(null=True)
    last_name = models.CharField(null=True)

    GUEST = "guest"
    SUPERUSER = "superuser"
    TECH = "tech"
    STAFF = "staff"
    REGIONAL = "regional"
    ROLES = {
        GUEST:     "Guest user",
        SUPERUSER: "Superuser",
        TECH:      "Tech support",
        STAFF:     "Staff",
        REGIONAL:  "Regional coordinator",
    }
    role = models.CharField(max_length=9, choices=ROLES)

    def role_name(self):
        return self.ROLES[self.role]

    # has_and_belongs_to_many :cases
    cases = models.ManyToManyField(Case, blank=True)

    # belongs_to :region
    region = models.ForeignKey(Region, on_delete=models.CASCADE, null=True)

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name()

darts/search/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(
        label = False,
        max_length = 140,
        widget = forms.TextInput(attrs={
            'class': 'usa-input',
            'id': 'search-field-en-big',
            'type': 'search',
            'name': 'search',
        })
    )

class UploadFileForm(forms.Form):
    title = forms.CharField(label="Document title", max_length=255)
    file = forms.FileField(
        label = "Upload a PDF or DOCX",
        widget = forms.FileInput(attrs={
            'class': 'usa-file-input',
            'id': 'file-input-single',
            'name': 'file-input-single',
            'type': 'file',
        })
    )
    public = forms.BooleanField(
        required=False,
        label='Is this a public document, or an internal document?',
        widget=forms.RadioSelect(
            choices=[
                (True, 'This is a public document'),
                (False, 'This is an internal document')
            ]
    ))

darts/search/views.py
from django.http import FileResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views import View

from .context_processors import current_user
from .forms import SearchForm, UploadFileForm
from .models import Document, Case
from .operations.document_search import DocumentSearch
from .operations.document_upload import DocumentUpload
from .operations.document_view import DocumentView
from .repositories.search_results import SearchResultsRepository
from .repositories.users import UsersRepository


class Search(View):

    def post(self, request):
        query = request.POST.get('query')
        context = {
            'form': SearchForm(request.POST),
            'query': query,
            'results': DocumentSearch(query, searcher = current_user(request)['current_user']).call(),
            'searched': True,
        }
        return render(request, 'search.html', context)

    def get(self, request):
        context = { 'form': SearchForm() }
        return render(request, 'search.html', context)


def set_user(request, **kwargs):
    request.session.update({"user.id": kwargs.get('id')})
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


class CaseView(View):

    def get(self, request, id):
        case = Case.objects.get(pk=id)
        return render(request, 'case.html', { 'case': case })


class Upload(View):

    def post(self, request):
        form = UploadFileForm(request.POST, request.FILES)
        match form.is_valid():
            case True:
                DocumentUpload().call(
                    request.FILES['file'],
                    request.POST.get('title'),
                    request.POST.get('public'),
                )
                return HttpResponseRedirect('/upload/')
            case False:
                return form

    def get(self, request):
        context = {
          'form': UploadFileForm(),
          'count': Document.objects.count
        }
        return render(request, 'upload.html', context)


def list(request):
    docs = Document.objects.all()
    return render(request, 'list.html', {'docs': docs})


def view_doc(request, id, slug=None):
    if slug == None:
        doc = Document.objects.get(pk=id)
        return redirect('document', id, doc.slug)

    buffer, filename, mimetype = DocumentView(id).call()
    return FileResponse(buffer, filename=filename, content_type=mimetype)

darts/search/templates/case.html
{% extends "layout.html" %}

{% block head %}
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin=""/>
  <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin=""></script>
  <style>
    #map {
      height: 300px;
      margin: 1.25rem 0;
      z-index: 1;
    }
  </style>
{% endblock head %}

{% block title %}{{ case.name }}{% endblock title %}

{% block content %}

<h1>{{ case.name }}</h1>
<h3>{{ case.location }}, {{ case.state }}</h3>

<div class="grid-row grid-gap">
  <div class="grid-col-7">
    <section class="usa-prose" id="description" aria-label="Case description">
      <!-- <h2>Case description</h2> -->
      {{ case.description|linebreaks }}
    </section>
    <section id="details" aria-label="Case details">
    {% include "partials/case/table.html" %}
    </section>
  </div>
  <div class="grid-col-5">
    <div id="map"></div>
    <div id="photos">
      <ul class="usa-card-group">
        {% for photo in case.photos %}
          {% include "partials/case/photo.html" %}
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

<section id="documents" aria-label="Case documents">
  <h2>Case documents</h2>
  {% if case.document_set.all|length > 0 %}
    {% include "partials/document_table.html" with docs=case.document_set.all %}
  {% else %}
    There are no public documents to show.
  {% endif %}
</section>

<script>
  var map = L.map('map').setView({{ case.lonlat }}, {{ case.zoom }});
  L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
  }).addTo(map);
  var marker = L.marker({{ case.lonlat }}).addTo(map);
</script>


{% endblock content %}

darts/search/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/uswds-init.min.js' %}" defer></script>
    {% block head %}{% endblock head %}

    <title>{% block title %}{% endblock title %} • DARTS</title>
  </head>
  <body>
    <main>
      <div class="grid-container">
        <div class="grid-row">
          <div class="grid-col">
            {% include "partials/nav.html" %}
          </div>
        </div>
        <div class="grid-row">
          <div class="grid-col">
            {% block content %}{% endblock content %}
          </div>
        </div>
      </div>
      {% block gridless %}{% endblock gridless %}
      {% include "partials/footer.html" %}
    </main>
  </body>
</html>

darts/search/templates/list.html
{% extends "layout.html" %}

{% block title %}List{% endblock %}

{% block content %}
<h1>Document list</h1>
{% if docs|length > 0 %}
  {% include "partials/document_table.html" with docs=docs %}
{% else %}
  No documents yet. <a href="/upload">Add one.</a>
{% endif %}
{% endblock content %}

darts/search/templates/search.html
{% extends "layout.html" %}

{% block title %}Search{% endblock %}

{% block content %}

<h1>Search ORDA DARTS</h1>

<section id="search" aria-label="Search ORDA DARTS">
  <form action="/search/" method="post" class="usa-search usa-search--big" role="search">
    <label class="usa-sr-only" for="search-field-en-big">Search</label>
    {% csrf_token %}
    {% for field in form %}
      {{ field }}
    {% endfor %}
    <button class="usa-button" type="submit">
      <span class="usa-search__submit-text">Search</span>
    </button>
  </form>
</section>

<style>
  span.highlight {
    font-weight: bold;
  }
</style>

<section id="search-results" aria-label="Search results">
  {% if searched %}
    <h2>Documents matching <q>{{ query }}</q></h2>

    {% if results|length > 0 %}
      <div class="grid-row grid-gap">
        <div>
          <ul class="usa-collection">
            {% for result in results %}
              {% include "partials/search_result.html" with result=result %}
            {% endfor %}
          </ul>
        </div>
      </div>
    {% else %}
      <p>No results for '{{ query }}'.</p>
    {% endif %}

    {% include "partials/pagination.html" %}

  {% endif %}
</section>

{% endblock content %}

darts/search/templates/upload.html
{% extends "layout.html" %}

{% block title %}Upload{% endblock %}

{% block content %}

<h1>Upload document</h1>
<p>
  {{ count }} documents in database
</p>

{% include "partials/form.html" with
    form=form
    action="/upload/"
    class="usa-form"
    enctype="multipart/form-data"
    %}

{% endblock content %}